# Use the latest version of ubuntu as the base image
FROM ubuntu:latest

# Update the package lists for need updates
RUN apt-get update

# Upgrade all packages
RUN apt-get upgrade -y

# launch Docker and Say Hello World
CMD echo "Hello World"